--
-- Copyright (C) 2011 ASIP Solutions, Inc. All rights reserved. 
-- Generated by ASIP Meister 2.3 on 2021/06/29 05:21:52 
--
--   int_port : internal port
--   ext_port : external port

-- Comment :

library IEEE;
  use IEEE.std_logic_1164.all;
  use IEEE.std_logic_arith.all;
  use IEEE.std_logic_unsigned.all;

entity fhm_index_w4 is
  port (
	clock_new    : in std_logic;
        reset_new    : in std_logic;
        enb_new      : in std_logic;
        data_in_new  : in std_logic_vector(3 downto 0);
        index_in : in std_logic_vector(31 downto 0);
        index_out : out std_logic_vector(31 downto 0)
        );
end fhm_index_w4;

architecture logic of fhm_index_w4 is
-- Your signal declaration here
type array_type1 is array (0 to 15) of integer; 
signal indexTable : array_type1:=( -1, -1, -1, -1, 2, 4, 6, 8,
                                   -1, -1, -1, -1, 2, 4, 6, 8 );

begin
  -- Your vhdl code here
  process (clock_new, reset_new, enb_new)

  variable upper : integer := 88;
  variable lower : integer := 0;
  variable cmpval : STD_LOGIC_VECTOR (31 downto 0);

  begin
  
      if (enb_new = '1') then
  cmpval :=
  	conv_std_logic_vector(indexTable(conv_integer(data_in_new)), 32) +
				conv_std_logic_vector(conv_integer(index_in), 32);

	  if (signed(cmpval) < lower) then
	    index_out <= conv_std_logic_vector(lower, 32);
	  elsif (signed(cmpval) > upper) then
	    index_out <= conv_std_logic_vector(upper, 32);
	  else
	    index_out <= cmpval;
	  end if;

      end if;
  end process;

end logic;


-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------
