--
-- Copyright (C) 2011 ASIP Solutions, Inc. All rights reserved. 
-- Generated by ASIP Meister 2.3 on 2021/06/29 05:21:55 
--
--   int_port : internal port
--   ext_port : external port

-- Comment :

library IEEE;
  use IEEE.std_logic_1164.all;
  use IEEE.std_logic_arith.all;

entity fhm_clamp_w4 is
  port (
	clock    : in std_logic;
        reset    : in std_logic;
        enb      : in std_logic;
        cmpval : in  STD_LOGIC_VECTOR (31 downto 0);
        greaterval   : in  STD_LOGIC_VECTOR (31 downto 0);
        lesserval   : in  STD_LOGIC_VECTOR (31 downto 0);
	dout   : out STD_LOGIC_VECTOR (31 downto 0)
        );
end fhm_clamp_w4;

architecture st of fhm_clamp_w4 is
-- Your signal declaration here

begin
  -- Your vhdl code here
  process (clock, reset, enb)
  begin
	  if (signed(cmpval) < signed(lesserval)) then
	    dout <= lesserval;
	  elsif (signed(cmpval) > signed(greaterval)) then
	    dout <= greaterval;
	  else
	    dout <= cmpval;
	  end if;
  end process;

end st;


-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------
