--
-- Copyright (C) 2011 ASIP Solutions, Inc. All rights reserved. 
-- Generated by ASIP Meister 2.3 on 2021/07/02 01:29:43 
--
--   int_port : internal port
--   ext_port : external port

-- Comment :

library IEEE;
  use IEEE.std_logic_1164.all;
  use IEEE.std_logic_arith.all;

entity fhm_minmax_w32 is
  port (
	clock    : in std_logic;
        reset    : in std_logic;
        enb      : in std_logic;
        din1 : in  STD_LOGIC_VECTOR (31 downto 0);
        din2   : in  STD_LOGIC_VECTOR (31 downto 0);
        doutMin   : out  STD_LOGIC_VECTOR (31 downto 0);
	doutMax   : out STD_LOGIC_VECTOR (31 downto 0)
        );
end fhm_minmax_w32;

architecture st of fhm_minmax_w32 is
-- Your signal declaration here

begin
  -- Your vhdl code here
process (clock, reset, enb)
begin
  if (signed(din1) < signed(din2)) then
    doutMin <= din1;
  else
    doutMin <= din2;
  end if;

if (signed(din1) > signed(din2)) then
  doutMax <= din1;
else
  doutMax <= din2;
end if;
end process;

end st;


-----------------------------------------
-- Generated by ASIP Meister ver.2.3.4 --
-----------------------------------------
